feedback/urls.py
from django.conf.urls import url
from . import views

app_name = 'feedback'

urlpatterns = [
    url(r'^$', view=views.home, name='feedback'),
    url(r'^postdata/$', view=views.get_feedback_data, name='get_feedback_data'),
    url(r'^form/$', view=views.feedback_form, name='feedback_form'),
    url(r'^list/$', view=views.feedback_list, name='feedback_list'),
    url(r'^(?P<fid>\d{1,4})/$', view=views.feedback_detail, name='feedback_detail'),
    url(r'^edit/(?P<fid>\d{1,4})/$', view=views.feedback_edit, name='feedback_edit'),
    url(r'^del/(?P<fid>\d{1,4})/$', view=views.feedback_delete, name='feedback_delete'),
    url(r'^login/$', view=views.login, name='login'),
    url(r'^logout/$', view=views.logout, name='logout'),
]

hello/urls.py
from django.conf.urls import url
from . import views

app_name = 'hello'

urlpatterns = [
    url(r'^home/$', view=views.home, name='hello-home'),
    url(r'^course/(\d{4})/$', view=views.course_year, name='hello-course-year'),
    url(r'^course/(?P<year>\d{4})/(?P<month>\d{2})/$', view=views.course_year_month, name='hello-course_year_month'),
    url(r'^redirect/$', view=views.view_redirect, name='course_redirect'),
    url(r'^contact/$', view=views.view_contact, name='contact'),
    url(r'^product/(?P<pid>\d+)/$', view=views.product_info, name='product_detail'),
    url(r'^help/$', view=views.help_center, name='help'),
    url(r'request/$', view=views.request_info, name='request_info')
]

tuturial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'learn/',include('learn.urls')),
    url(r'state/',include('state.urls')),
    url(r'^hello/', include('hello.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'^tutor/$', view=views.tutor, name='tutor'),
    url(r'^admin/', admin.site.urls),
]

feedback/models.py
from django.db import models


# Create your models here.
class Feedback(models.Model):
    CATEGORIES = (
        ('产品质量', '产品质量'),
        ('网站使用', '网站使用'),
        ('支付购买', '支付购买'),
        ('客户服务', '客户服务'),
    )
    STATUS = (
        ('待处理', '待处理'),
        ('处理中', '处理中'),
        ('已处理', '已处理'),
    )
    subject = models.CharField('主题', max_length=100)
    category = models.CharField('分类', choices=CATEGORIES, max_length=20)
    username = models.CharField('姓名', max_length=20)
    email = models.EmailField('邮箱', max_length=200)
    screenshot = models.FileField('问题截图', upload_to='uploads/')
    description = models.TextField('问题描述')
    subscription = models.BooleanField('订阅资讯', default=True)
    status = models.CharField('处理状态', choices=STATUS, max_length=20)
    posted_time = models.DateTimeField('提交时间', auto_now_add=True)

feedback/forms.py
from django import forms
from .models import Feedback
from django.core import validators
from django.core.exceptions import ValidationError

"""表单模型类"""


class FeedbackForm(forms.Form):
    subject = forms.CharField(label='主题', max_length=20,
                              validators=[validators.MinLengthValidator(2, message='主题不能小于2个字符！')],
                              help_text='问题标题', widget=forms.TextInput(attrs={'class': 'form-control'}))
    category = forms.ChoiceField(label='分类', choices=Feedback.CATEGORIES,
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    username = forms.CharField(label='姓名',widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(label='邮箱', widget=forms.TextInput(attrs={'class': 'form-control'}))
    screenshot = forms.FileField(label='问题截图', required=False)
    description = forms.CharField(label='问题描述', widget=forms.Textarea(attrs={'class': 'form-control'}))
    subscription = forms.BooleanField(label='订阅资讯', required=False)
    status = forms.ChoiceField(label='处理状态', required=False, choices=Feedback.STATUS,
                               widget=forms.Select(attrs={'class': 'form-control'}))
    posted_time = forms.DateTimeField(label='发布时间', required=False,
                                      widget=forms.TextInput(attrs={'class': 'form-control'}))


class ContactForm(forms.Form):
    username = forms.CharField()
    group = forms.ChoiceField()
    mobile = forms.CharField()
    star = forms.BooleanField()


def validate_even(value):
    if value % 2 != 0:
        raise ValidationError(f'数字{value}不是一个偶数！')


class TestForm(forms.Form):
    name = forms.CharField(label='姓名', max_length=6, validators=[validators.MinLengthValidator(2, message='最少需要2个字符!')])
    email = forms.EmailField(label='邮箱', max_length=100)
    alt_email = forms.CharField(label='备用邮箱', validators=[validators.EmailValidator(message='邮箱格式错误！')])
    site = forms.URLField(label='网址')
    mobile = forms.CharField(label='手机号', validators=[validators.RegexValidator(r'^1(3|4|5|7|8)[0-9]\d{8})$')])
    ip = forms.CharField(label='IP地址', validators=[validators.validate_ipv4_address])
    age = forms.IntegerField(label='年龄', validators=[
        validators.MaxValueValidator(100, message='年龄最大为100岁！'),
        validators.MinValueValidator(18, message='年龄最小为18岁！'),
    ])
    price = forms.DecimalField(label='价格')
    number = forms.IntegerField(validators=[validate_even])

feedback/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse
from .models import Feedback
from .forms import FeedbackForm


# Create your views here.
def home(request):
    context = {
        'categories': Feedback.CATEGORIES
    }
    if request.method == 'POST':
        f = Feedback()
        f.subject = request.POST.get('subject', '')
        f.category = request.POST.get('category', '')
        f.username = request.POST.get('username', '')
        f.email = request.POST.get('email', '')
        f.screenshot = ''
        f.description = request.POST.get('description', '')
        f.subscription = 'subscription' in request.POST
        f.status = '待处理'
        f.save()
        return HttpResponse('问题提交成功')
    return render(request, 'feedback/feedback.html', context)


def feedback_form(request):
    form = FeedbackForm(initial={'subject': '反馈问题标题'})
    if request.method == 'POST':
        form = FeedbackForm(request.POST, request.FILES)
        if form.is_valid():
            # data = dict(form.cleaned_data)
            # feedback = Feedback(**form.cleaned_data)
            # feedback.status = '待处理'
            # feedback.save()
            if request.FILES['screenshot']:
                upload_file(request.FILES['screenshot'])
            return redirect('/')
    return render(request, 'feedback/feedback-form.html', {'form': form})


def get_feedback_data(request):
    if request.method == 'GET':
        data = dict(request.GET)
        return HttpResponse(str(data))


def upload_file(f):
    with open('uploads\{}'.format(f.name), 'wb+') as file:
        for chunk in f.chunks():
            file.write(chunk)


def feedback_list(request):
    """信息列表页"""
    if 'admin' in request.session:
        q = request.GET.get('q', '')
        items = Feedback.objects.all().filter(subject__contains=q).order_by('-posted_time')
        return render(request, 'feedback/feedback-list.html', {'items': items})
    else:
        return redirect(reverse('feedback:login'))


def feedback_detail(request, fid):
    """信息详情展示页"""
    # feedback = Feedback.objects.get(pk=fid)
    feedback = get_object_or_404(Feedback, pk=fid)
    return render(request, 'feedback/feedback-detail.html', {'item': feedback})


def feedback_edit(request, fid):
    """编辑特定id信息"""
    fb = get_object_or_404(Feedback, pk=fid)
    form = FeedbackForm(initial={
        'subject': fb.subject,
        'category': fb.category,
        'username': fb.username,
        'email': fb.email,
        'screenshot': fb.screenshot,
        'description': fb.description,
        'subscription': fb.subscription,
        'status': fb.status,
        'posted_time': fb.posted_time,
    })
    if request.method == 'POST':
        form = FeedbackForm(request.POST, request.FILES)
        if form.is_valid():
            # fb.subject = form.cleaned_data['subject']
            for k, v in form.cleaned_data.items():
                setattr(fb, k, v)
            fb.save()
            return redirect(reverse('feedback:feedback_list'))
    return render(request, 'feedback/feedback-edit.html', {'form': form})


def feedback_delete(request, fid):
    """删除信息"""
    f = get_object_or_404(Feedback, pk=fid)
    f.delete()
    return redirect(reverse('feedback:feedback_list'))


def login(request):
    """管理员登录"""
    if request.method == 'POST':
        username = request.POST.get('username', None)
        pwd = request.POST.get('pwd', None)
        if username == 'Tom' and pwd == '123456':
            request.session['admin'] = username
            return redirect(reverse('feedback:feedback_list'))
        else:
            return redirect(reverse('feedback:login'))
    return render(request, 'feedback/login.html')


def logout(request):
    """退出登录"""
    if 'admin' in request.session:
        request.session.flush()
    return redirect(reverse('feedback:login'))

feedback/templates/feedback/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FMS 问题反馈管理系统</title>
    <script src="http://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <nav class="navbar navbar-default" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">FMS</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">首页</a></li>
                </ul>
                <form action="{% url 'feedback:feedback_list' %}" class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input name="q" type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ request.session.admin }} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">发布反馈信息</a></li>
                            <li><a href="#">信息列表</a></li>
                            <li><a href="{% url 'feedback:logout' %}">退出登录</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </div>
    <div class="row">
        <ol class="breadcrumb">
            <li>
                <a href="#">首页</a>
            </li>
            <li class="active">Link</li>
        </ol>
    </div>
    <div class="row">
        {% block main_content %}

        {% endblock %}
    </div>
    <div class="row">
        <div class="text-center">
            &copy;Cyril 你好呀
        </div>
    </div>
</div>
</body>
</html>

feedback/templates/feedback/feedback-detail.html
{% extends 'feedback/base.html' %}
{% block main_content %}
    <table class="table table-bordered">
        <tr>
            <td>编号</td>
            <td>{{ item.id }}</td>
        </tr>
        <tr>
            <td>主题</td>
            <td>{{ item.subject }}</td>
        </tr>
        <tr>
            <td>分类</td>
            <td>{{ item.category }}</td>
        </tr>
        <tr>
            <td>姓名</td>
            <td>{{ item.username }}</td>
        </tr>
        <tr>
            <td>邮箱</td>
            <td>{{ item.email }}</td>
        </tr>
        <tr>
            <td>问题截图</td>
            <td>{{ item.screenshot }}</td>
        </tr>
        <tr>
            <td>问题描述</td>
            <td>{{ item.description }}</td>
        </tr>
        <tr>
            <td>资讯订阅</td>
            <td>{{ item.subscription|yesno:'已订阅,未订阅' }}</td>
        </tr>
        <tr>
            <td>处理状态</td>
            <td>{{ item.status }}</td>
        </tr>
        <tr>
            <td>发布时间</td>
            <td>{{ item.posted_time }}</td>
        </tr>
        <tr>
            <td></td>
            <td>
                <a href="{% url 'feedback:feedback_list' %}" class="btn btn-default">返回列表</a>
            </td>
        </tr>
    </table>
{% endblock %}

feedback/templates/feedback/feedback-edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="#" method="post" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4>问题反馈</h4>
                    </div>
                    <div class="panel-body">
                        {{ form.errors }}
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.subject.label }}
                            </label>
                            <div class="col-md-10">
                                {{ form.subject }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.category.label }}
                            </label>
                            <div class="col-md-4">
                                {{ form.category }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.username.label }}
                            </label>
                            <div class="col-md-10">
                                {{ form.username }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.email.label }}
                            </label>
                            <div class="col-md-10">
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.screenshot.label }}
                            </label>
                            <div class="col-md-10">
                                {{ form.screenshot }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.description.label }}
                            </label>
                            <div class="col-md-10">
                                {{ form.description }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.subscription.label }}
                            </label>
                            <div class="col-md-10">
                                {{ form.subscription }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.status.label }}
                            </label>
                            <div class="col-md-4">
                                {{ form.status }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.posted_time.label }}
                            </label>
                            <div class="col-md-4">
                                {#                                {{ form.posted_time }}#}
                                <input type="text" class="form-control" id="{{ form.posted_time.id_for_label }}"
                                       name="{{ form.posted_time.html_name }}" value="{{ form.posted_time.value |date:'Y-m-d H:i'}}">
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-md-10 col-md-offset-2">
                                <input type="submit" value="提交" class="btn btn-primary">
                                <input type="submit" value="重置" class="btn btn-default">
                                <a href="{% url 'feedback:feedback_list' %}" class="btn btn-default">返回列表</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>

feedback/templates/feedback/feedback-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="#" method="post" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4>问题反馈</h4>
                    </div>
                    <div class="panel-body">
                        {{ form.errors}}
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.subject.label }}
                            </label>
                            <div class="col-md-10">
                                {{ form.subject }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.category.label }}
                            </label>
                            <div class="col-md-4">
                                {{ form.category }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.username.label }}
                            </label>
                            <div class="col-md-10">
                                {{ form.username }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.email.label }}
                            </label>
                            <div class="col-md-10">
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.screenshot.label }}
                            </label>
                            <div class="col-md-10">
                                {{ form.screenshot }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.description.label }}
                            </label>
                            <div class="col-md-10">
                                {{ form.description }}
                            </div>
                        </div><div class="form-group">
                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">
                                {{ form.subscription.label }}
                            </label>
                            <div class="col-md-10">
                                {{ form.subscription }}
                            </div>
                        </div>
{#                        <div class="form-group">#}
{#                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">#}
{#                                {{ form.status.label }}#}
{#                            </label>#}
{#                            <div class="col-md-4">#}
{#                                {{ form.status }}#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="form-group">#}
{#                            <label class="control-label col-md-2" for="{{ form.subject.id_for_label }}">#}
{#                                {{ form.posted_time.label }}#}
{#                            </label>#}
{#                            <div class="col-md-4">#}
{#                                {{ form.posted_time }}#}
{#                            </div>#}
{#                        </div>#}
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-md-10 col-md-offset-2">
                                <input type="submit" value="提交" class="btn btn-primary">
                                <input type="submit" value="重置" class="btn btn-default">
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>

feedback/templates/feedback/feedback-list.html
{% extends 'feedback/base.html' %}
{% block main_content %}
    <table class="table table-hover">
        <tr>
            <td>#</td>
            <td>主题</td>
            <td>分类</td>
            <td>状态</td>
            <td>资讯订阅</td>
            <td>发布时间</td>
            <td>操作</td>
        </tr>
        {% for item in items %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.subject }}</td>
                <td>{{ item.category }}</td>
                <td>{{ item.status }}</td>
                <td>{{ item.subscription|yesno:'<span class ="label label-success">已定阅</span>,<span class ="label label-danger">未订阅</span>'|safe }}</td>
                <td>{{ item.posted_time }}</td>
                <td>
                    <a href=" {% url 'feedback:feedback_detail' fid=item.id %}" class="btn btn-sm btn-default"
                       title="浏览"><i class="fa fa-search"></i></a>
                    <a href="{% url 'feedback:feedback_edit' fid=item.id %}" class="btn btn-sm btn-default"
                       title="编辑"><i
                            class="fa fa-pencil"></i></a>
                    <a href="{% url 'feedback:feedback_delete' fid=item.id %}" class="btn btn-sm btn-default"
                       title="删除"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

feedback/templates/feedback/feedback.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>问题反馈</title>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">

    </div>
    <div class="row">
        <form action="#" method="post"  class="form-horizontal">
        {%  csrf_token %}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4>问题反馈</h4>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="control-label col-md-2" for="subject">主题</label>
                        <div class="col-md-4">
                            <input class="form-control" type="text" id="subject" name="subject">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2" for="category">分类</label>
                        <div class="col-md-2">
                            <select class="form-control" name="category" id="category">
                                {% for category in categories %}
                                    <option value="{{ category.0 }}">{{ category.1 }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2" for="username">姓名</label>
                        <div class="col-md-4">
                            <input class="form-control" type="text" id="username" name="username">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2" for="email">邮箱</label>
                        <div class="col-md-4">
                            <input class="form-control" type="email" id="email" name="email" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2" for="screenshot">问题截图</label>
                        <div class="col-md-10">
                            <input type="file" id="screenshot" name="screenshot">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2" for="description">问题描述</label>
                        <div class="col-md-4">
                            <textarea class="form-control" name="description" id="description" cols="30"
                                      rows="10"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2" for="subscription">订阅资讯</label>
                        <div class="col-md-10">
                            <input type="checkbox" id="subscription" name="subscription">
                        </div>
                    </div>


                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-2">
                            <input type="submit" class="btn btn-primary" value="提交">
                            <input type="reset" class="btn btn-default " value="重置">
                        </div>
                    </div>
        </form>
    </div>
</div>
</div>
</div>

</body>
</html>

feedback/templates/feedback/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>管理员登录</title>
</head>
<body>
<h1>管理员登录</h1>
<form action="#" method="post">
    {% csrf_token %}
    <p>用户名：<input type="text" name="username"></p>
    <p>密码：<input type="password" name="pwd"></p>
    <p><input type="submit" value="登录"></p>
</form>
</body>
</html>